Project.Net/Models/DataModel/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Net.Models.DataModel
{
    public class Note
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public int Type { get; set; }
        [Required]
        public string AttrName { get; set; }
        public ICollection<Banner> Banners { get; set; }
        public ICollection<ProductNote> ProductNotes { get; set; }
    }
}

Project.Net/Areas/Admin/Controllers/NotesController.cs
using Project.Net.Models.DataModel;
using Project.Net.Models.Respositories;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Net.Areas.Admin.Controllers
{
  
    public class NotesController : Controller
    {
        Respository<Note> _note;
        Respository<Product> _pro;
        Respository<Banner> _ban;

        public NotesController()
        {
            _note = new Respository<Note>();
            _pro = new Respository<Product>();
            _ban = new Respository<Banner>();
        }
        // GET: Admin/Notes
        public ActionResult Index(string table_search)
        {
            var data = _note.GetAll().AsQueryable();
            if (!String.IsNullOrEmpty(table_search))
            {
                data = data.AsQueryable().Where(x => x.AttrName.Contains(table_search.ToLower()));

                //data = data.Where(x => x.ProductName.Contains(table_search.ToLower())).ToList();

                // Dữ lại tham số tìm kiếm
                ViewBag.key = table_search;
            }
            return View(data);
        }
        // GET: Admin/Notes/Details/5
        public ActionResult Details(int id)
        {
            return View(_note.Get(id));
        }
        // GET: Admin/Notes/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Admin/Notes/Create
        [HttpPost]
        public ActionResult Create(Note n)
        {
            if (ModelState.IsValid)
            {
                if (_note.Add(n))
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
            return View();
        }
        // GET: Admin/Notes/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_note.Get(id));
        }
        // POST: Admin/Notes/Edit/5
        [HttpPost]
        public ActionResult Edit(Note n)
        {
            if (ModelState.IsValid)
            {
                if (_note.Edit(n))
                {
                    return RedirectToAction("Index");
                }
                return View();
            }
            return View();
        }

        // GET: Admin/Notes/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    try
        //    {
        //        if (_pro.GetAll().Any(x => x.NoteId == id || _ban.GetAll().Any(b=>b.NoteId==id)))
        //        {
        //            TempData["msg"] = new ResponseMessage()
        //            {
        //                Type = "alert-danger",
        //                Message = "Thất bại! Đang có sản phẩm thuộc note này"
        //            };
        //            return RedirectToAction("Index");
        //        }
        //        _note.Remove(id);
        //        TempData["msg"] = new ResponseMessage()
        //        {
        //            Type = "alert-success",
        //            Message = "Xóa thành công!"
        //        };
        //    }
        //    catch (Exception ex)
        //    {

        //        TempData["msg"] = new ResponseMessage()
        //        {
        //            Type = "alert-danger",
        //            Message = ex.Message
        //        };
        //    }
        //    return RedirectToAction("Index");
        //}

        
    }
}

Project.Net/Areas/Admin/Views/Notes/Create.cshtml
@model Project.Net.Models.DataModel.Note

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Note</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.RadioButtonFor(model => model.Type, 1, new { Checked = "checked" })Banner
                            @Html.RadioButtonFor(model => model.Type, 2)Product
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AttrName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AttrName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AttrName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- /.box-body -->
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        <!-- /.box-footer-->
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project.Net/Areas/Admin/Views/Notes/Details.cshtml
@model Project.Net.Models.DataModel.Note

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttrName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttrName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project.Net/Areas/Admin/Views/Notes/Edit.cshtml
@model Project.Net.Models.DataModel.Note

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Note</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.RadioButtonFor(model => model.Type, 1, new { Checked = "checked" })Banner
                            @Html.RadioButtonFor(model => model.Type, 2)Product
                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AttrName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AttrName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AttrName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- /.box-body -->
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        <!-- /.box-footer-->
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project.Net/Areas/Admin/Views/Notes/Index.cshtml
@using Project.Net.Models.DataModel
@model IEnumerable<Project.Net.Models.DataModel.Note>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
@if (TempData["msg"] != null)
{
    ResponseMessage res = (ResponseMessage)TempData["msg"];
    <div class="alert @res.Type">@res.Message</div>
}
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
        <div class="box-tools">
            @using (Html.BeginForm("Index", "Notes", FormMethod.Get))
            {
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" value="@ViewBag.key" class="form-control pull-right" placeholder="Search">

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="box-body">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AttrName)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (item.Type == 1)
                        {
                            <span>Banner</span>
                        }
                        @if (item.Type == 2)
                        {
                           <span>Product</span>
                        }
                        
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AttrName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
    <!-- /.box-body -->
    @*<div class="box-footer">
           Phân trang
        </div>*@
    <!-- /.box-footer-->
</div>