Project.Net/Models/DataModel/AttributeType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Project.Net.Models.DataModel
{
    public class AttributeType
    {
        [Key]
        
        public int AttrTypeId { get; set; }
        [Required]
        public string TypeName { get; set; }
        [Required]
        public int OrderBy { get; set; }
        [Required]
        public bool Status { get; set; }
        public ICollection<Attributes> Attributes { get; set; }
    }
}

Project.Net/Models/DataModel/Attributes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Project.Net.Models.DataModel
{
    public class Attributes
    {
        [Key]
        
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Value { get; set; }
        [Required]
        public int TypeId { get; set; }
        [Required]
        public bool Status { get; set; }
        [ForeignKey("TypeId")]
        public virtual AttributeType AttributeTypes { get; set; }
        public ICollection<ProductAttr> ProductAttrs { get; set; }
    }
}

Project.Net/Areas/Admin/Controllers/AttributesController.cs
using Project.Net.Models.DataModel;
using Project.Net.Models.Respositories;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Net.Areas.Admin.Controllers
{
    public class AttributesController : Controller
    {
        Respository<AttributeType> _atty;
      
        Respository<Attributes> _attr;
        Respository<Product> _pro;
        Respository<ProductAttr> _prat;
        public AttributesController()
        {
            _attr = new Respository<Attributes>();
            _atty = new Respository<AttributeType>();
            _pro = new Respository<Product>();
            _prat = new Respository<ProductAttr>();
        }
        // GET: Admin/Attributes
        [CustomAuthAttributes(Roles = "VIEW")]
        public ActionResult Index(string table_search)
        {
            var data = _attr.GetAll().AsQueryable().Include(x => x.AttributeTypes);
            if (!String.IsNullOrEmpty(table_search))
            {
                data = data.AsQueryable().Where(x => x.Name.Contains(table_search.ToLower()));

                //data = data.Where(x => x.ProductName.Contains(table_search.ToLower())).ToList();

                // Dữ lại tham số tìm kiếm
                ViewBag.key = table_search;
            }
            return View(data);
        }

        // GET: Admin/Attributes/Details/5
        public ActionResult Details(int id)
        {
            return View(_attr.Get(id));
        }

        // GET: Admin/Attributes/Create
        public ActionResult Create()
        {
            ViewBag.TypeId = new SelectList(_atty.GetAll(), "AttrTypeId", "TypeName");
            return View();
        }

        // POST: Admin/Attributes/Create
        [CustomAuthAttributes(Roles = "ADD")]
        [HttpPost]
        public ActionResult Create(Attributes attr)
        {
            ViewBag.TypeId = new SelectList(_atty.GetAll(), "AttrTypeId", "TypeName");
            if (ModelState.IsValid)
            {
                if (_attr.Add(attr))
                {
                    return RedirectToAction("Index");

                }
                return View();
            }
            return View();
        }

        // GET: Admin/Attributes/Edit/5
        [CustomAuthAttributes(Roles = "EDIT")]
        public ActionResult Edit(int id)
        {
            ViewBag.TypeId = new SelectList(_atty.GetAll(), "AttrTypeId", "TypeName");
            return View(_attr.Get(id));
        }

        // POST: Admin/Attributes/Edit/5
        [CustomAuthAttributes(Roles = "EDIT")]
        [HttpPost]
        public ActionResult Edit(Attributes attr)
        {
            ViewBag.TypeId = new SelectList(_atty.GetAll(), "AttrTypeId", "TypeName");
            if (ModelState.IsValid)
            {
                if (_attr.Edit(attr))
                {
                    return RedirectToAction("Index");

                }
                return View();
            }
            return View();
        }

        // GET: Admin/Attributes/Delete/5
        [CustomAuthAttributes(Roles = "DELETE")]
        public ActionResult Delete(int id)
        {
            try
            {
                if (_prat.GetAll().Any(x => x.AttrId== id))
                {
                    TempData["msg"] = new ResponseMessage()
                    {
                        Type = "alert-danger",
                        Message = "Thất bại! Thuộc tính đang có sản phẩm"
                    };
                    return RedirectToAction("Index");
                }
                _attr.Remove(id);
                TempData["msg"] = new ResponseMessage()
                {
                    Type = "alert-success",
                    Message = "Xóa thành công!"
                };
            }
            catch (Exception ex)
            {

                TempData["msg"] = new ResponseMessage()
                {
                    Type = "alert-danger",
                    Message = ex.Message
                };
            }
            return RedirectToAction("Index");
        }

        // POST: Admin/Attributes/Delete/5
        
    }
}

Project.Net/Areas/Admin/Views/Attributes/Create.cshtml
@using Project.Net.Models.DataModel;
@model Project.Net.Models.DataModel.Attributes

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Attributes</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TypeId, "TypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Status)
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <!-- /.box-body -->
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <!-- /.box-footer-->
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project.Net/Areas/Admin/Views/Attributes/Details.cshtml
@model Project.Net.Models.DataModel.Attributes

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Attributes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AttributeTypes.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTypes.TypeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project.Net/Areas/Admin/Views/Attributes/Edit.cshtml
@model Project.Net.Models.DataModel.Attributes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Attributes</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TypeId, "TypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Status)
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- /.box-body -->
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        <!-- /.box-footer-->
    </div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project.Net/Areas/Admin/Views/Attributes/Index.cshtml
@using Project.Net.Models.DataModel;
@model IEnumerable<Project.Net.Models.DataModel.Attributes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
        <div class="box-tools">
            @using (Html.BeginForm("Index", "Attributes", FormMethod.Get))
            {
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" value="@ViewBag.key" class="form-control pull-right" placeholder="Search">

                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="box-body">

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AttributeTypes.TypeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Value)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AttributeTypes.TypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
    <!-- /.box-body -->
    @*<div class="box-footer">
            Phân trang
        </div>*@
    <!-- /.box-footer-->
</div>